name: Build and Push to Aliyun

on:
  push:
    branches:
      - main  # 当你向 main 分支 push 代码时触发
    paths-ignore:
          - 'helm/**'
          - 'README.md'
          - '.gitignore'
  workflow_dispatch: # 额外添加这个：允许你在 GitHub 页面上点击按钮手动触发（方便调试）

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤 1: 提取短哈希并存入环境变量
      - name: Set Short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Aliyun ACR
        uses: docker/login-action@v3
        with:
          registry: crpi-zwbmpse5bz48kucd.cn-shanghai.personal.cr.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # 步骤 2: 使用 ${{ env.sha_short }}
          tags: |
            crpi-zwbmpse5bz48kucd.cn-shanghai.personal.cr.aliyuncs.com/amaxzhong/python-app:latest
            crpi-zwbmpse5bz48kucd.cn-shanghai.personal.cr.aliyuncs.com/amaxzhong/python-app:${{ env.sha_short }}