name: Build and Push to Aliyun

on:
  push:
    branches:
      - main  # 当你向 main 分支 push 代码时触发
    paths-ignore:
          - 'helm/**'
          - 'README.md'
          - '.gitignore'
  workflow_dispatch: # 额外添加这个：允许你在 GitHub 页面上点击按钮手动触发（方便调试）

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤 1: 提取短哈希并存入环境变量
      - name: Set Short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Aliyun ACR
        uses: docker/login-action@v3
        with:
          registry: crpi-zwbmpse5bz48kucd.cn-shanghai.personal.cr.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # 步骤 2: 使用 ${{ env.sha_short }}
          tags: |
            crpi-zwbmpse5bz48kucd.cn-shanghai.personal.cr.aliyuncs.com/amaxzhong/python-app:latest
            crpi-zwbmpse5bz48kucd.cn-shanghai.personal.cr.aliyuncs.com/amaxzhong/python-app:${{ env.sha_short }}


      - name: Update Helm Image Tag
        run: |
          # 1. Update the tag in your values file
          # This assumes your helm/values.yaml has a structure like `image: { tag: "..." }`
          # We use 'sed' to replace the old tag with the new short SHA
          # sed -i 's/tag: .*/tag: "${{ env.sha_short }}"/g' helm/values.yaml
          # recommend to use yq command to replace tag value
          yq -i '.image.tag = "${{ env.sha_short }}"' helm/values.yaml

          # 2. Configure Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # 3. Commit and Push
          git add helm/values.yaml
          git commit -m "chore: update image tag to ${{ env.sha_short }} [skip ci]"
          git push